clear()
sleep(0.1)
print("🍝" *40)
sleep(0.1)
print("S      P      A      G      H      E      T      T      I")
sleep(0.1)
print("🍝" *40)

sleep(0.5)

clear()
print("🔪")  
print(" ")
print("     🍅")
print("     ")
print("     ")
print("     ")
print("     ")
print("     🍽️")
sleep(0.5)
clear()
sleep(0.5)
print(" ")  
print("  🔪 ")
print("     🍅")
print("     ")
print("     ")
print("     ")
print("     ")
print("     🍽️")
sleep(0.5)
clear()
sleep(0.5)
print(" ")  
print("   ")
print("     💥")
print("     ")
print("     ")
print("     ")
print("     ")
print("     🍽️")
sleep(0.5)
clear()
sleep(0.5)
print(" ")  
print("   ")
print("     ")
print("     🩸")
print("     ")
print("     ")
print("     ")
print("     🍽️")
sleep(0.5)
clear()
sleep(0.5)
print(" ")  
print("   ")
print("     ")
print("     ")
print("     🩸")
print("     ")
print("     ")
print("     🍽️")
sleep(0.5)
clear()
sleep(0.5)
print(" ")  
print("   ")
print("     ")
print("     ")
print("     ")
print("     🩸")
print("     ")
print("     🍽️")
sleep(0.5)
clear()
sleep(0.5)
print(" ")  
print("   ")
print("     ")
print("     ")
print("     ")
print("     ")
print("     🩸")
print("     🍽️")
sleep(0.5)
clear()
sleep(0.5)
print(" ")  
print("   ")
print("     ")
print("     ")
print("     ")
print("     ")
print("     ")
print("     🍝")
for i in range(2):
    sleep(0.1)
    clear()
    sleep(0.1)
    print(" ")  
    print("   ")
    print("     ")
    print("     ")
    print("     ")
    print("     ")
    print("     ")
    print("    ✨🍝")
    sleep(0.1)
    clear()
    sleep(0.1)
    print(" ")  
    print("   ")
    print("     ")
    print("     ")
    print("     ")
    print("     ")
    print("     ")
    print("       🍝✨")