from time import sleep
from os import system
clear = lambda : system("clear")

for i in range(2):
    print("🥐   " *20)
    sleep(0.1)
    print("   🥯   " *20)
    sleep(0.1)
    print("🍞   " *20)
    sleep(0.1)
    print("   🥖   " *20)
    sleep(0.1)
    print("🥞      "*20)
    sleep(0.1)
    print("   🧇   "*20)
    sleep(0.1)
    print("🌭   "*20)
    sleep(0.1)
    print("   🍕   "*20)
    sleep(0.1)

burger = "🍔"

for y in range(3, 31, 3):
    print(y,y * burger)
    sleep(0.1)

print("   🍔🍔🍔🍔🍔🍔🍔🍔🍔🍔🍔🍔🍔🍔🍔🍔🍔🍔🍔🍔🍔🍔🍔🍔🍔🍔🍔🍔🍔🍔🍔 COOKING CATASTROPHE CHAOS ")
sleep(0.2)

for x in range(30, 2, -3):
    print(x,x * burger)
    sleep(0.1)


for i in range(2):
    print("🥐   " *20)
    sleep(0.1)
    print("   🥯   " *20)
    sleep(0.1)
    print("🍞   " *20)
    sleep(0.1)
    print("   🥖   " *20)
    sleep(0.1)
    print("🥞      "*20)
    sleep(0.1)
    print("   🧇   "*20)
    sleep(0.1)
    print("🌭   "*20)
    sleep(0.1)
    print("   🍕   "*20)
    sleep(0.1)

print("💭")
print("🍲👩‍🍳            📖")
print("♨️")
sleep(0.5)
clear()
sleep(0.5)
print("💭")
print("🍲  👩‍🍳           📖")
print("♨️")
sleep(0.5)
clear()
sleep(0.5)
print("💭")
print("🍲     👩‍🍳        📖")
print("♨️")
sleep(0.5)
clear()
sleep(0.5)
print("💭")
print("🍲       👩‍🍳      📖")
print("♨️")
sleep(0.5)
clear()
sleep(0.5)
print("💭")
print("🍲         👩‍🍳    📖")
print("♨️")
sleep(0.5)
clear()
sleep(0.5)
print("💭")
print("🍲           👩‍🍳  📖")
print("♨️")